variables:
  CURRENT_RELEASE: 4.2
  NEXT_RELEASE: 4.3

workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

default:
  tags:
    - docker

pages:
  stage: build
  image: python:3
  artifacts:
    paths:
      - public
  script:
    - pip3 install -r requirements.txt
    - git submodule update --init --recursive
    - python3 ./g2g-report.py --current-release "${CURRENT_RELEASE}" --next-release "${NEXT_RELEASE}"
