workflow:
 rules:
   - if: '$CI_PIPELINE_SOURCE == "push"'
     when: never
   - when: always

default:
  tags:
    - docker

pages:
  stage: build
  image: python:3
  artifacts:
    paths:
      - public
  script:
    - pip3 install -r requirements.txt
    - git submodule update --init --recursive
    - python3 ./g2g-report.py --dist dom0-fc32 dom0-fc25 vm-fc32 vm-fc33 vm-fc34 vm-fc35 vm-centos8 vm-buster vm-bullseye vm-gentoo vm-gentoo-minimal vm-gentoo-xfce
